POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "hi2",
    "author": "78",
    "url": "78",
    "likes": 78
}

# DELETE  http://localhost:3001/api/blogs/66082568b15e085e17dea72c

# GET  http://localhost:3001/api/blogs