
# POST http://localhost:3001/api/blogs/blog
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpY2ggbGVlIiwiaWQiOiI2NjBkNTdiOTI5YTM0NTc5MzNmYTQ5MzQiLCJpYXQiOjE3MTIzNDgyNzZ9.IFKa0kTRimb01x6zD24QvvT3sMr0RSRIqBiwDiDfV6s

# {
#     "title": "test for rich666",
#     "author": "78",
#     "url": "78",
#     "likes": 78,
#     "user": "660d57b929a3457933fa4934"
# }

# DELETE  http://localhost:3001/api/blogs/6608673e391331305abca878

# GET  http://localhost:3001/api/blogs

# PUT http://localhost:3001/api/blogs/660833ea391331305abca876
# Content-Type: application/json

# {
#     "title": "rich is a dog2",
#     "author": "78",
#     "url": "78",
#     "likes": 78
# }

# POST http://localhost:3001/api/users/user
# Content-Type: application/json

# {
#     "username": "dog dudu2",
#     "name": "dudu",
#     "password": "password123"
# }


# POST http://localhost:3001/api/login
# Content-Type: application/json

# {
#     "username": "rich lee",
#     "password": "password1234"
# }


DELETE http://localhost:3001/api/blogs/66107a615cb52aee271ea004
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpY2ggbGVlIiwiaWQiOiI2NjBkNTdiOTI5YTM0NTc5MzNmYTQ5MzQiLCJpYXQiOjE3MTIzNDgyNzZ9.IFKa0kTRimb01x6zD24QvvT3sMr0RSRIqBiwDiDfV6s

